services:
  - type: web
    name: cybershield-api
    payload:
      # This tells Render to only trigger a deploy if files in 'backend' change
      paths:
        - backend/**
    rootDirectory: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
